main: com.cavetale.mytems.MytemsPlugin

name: Mytems
description: Items framework and collection

version: 0.1
api-version: '1.21.10'

author: StarTux
website: https://github.com/StarTux/Mytems

depend: [Core, WorldMarker]
softdepend: []

commands:

  mytems:
    aliases: []
    description: Mytems Command
    permission: mytems.mytems
    usage: /mytems

  openshulker:
    aliases: []
    description: Open shulker box in hand
    permission: mytems.openshulker
    usage: /openshulker


permissions:

  mytems.mytems:
    description: Use /mytems
    default: op

  mytems.openshulker:
    description: Use /openshulker
    default: false

  mytems.openshulker.click:
    description: Open shulker boxes by right clicking them in your inventory
    default: false