package com.cavetale.mytems.item.equipment;

import com.cavetale.mytems.Mytems;
import java.util.HashMap;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import net.kyori.adventure.text.format.TextColor;
import static net.kyori.adventure.text.format.NamedTextColor.*;
import static net.kyori.adventure.text.format.TextColor.color;

@RequiredArgsConstructor @SuppressWarnings("LineLength")
public enum EquipmentType {
    GOLDEN_QUIVER(Mytems.GOLDEN_QUIVER, EquipmentVariant.QUIVER, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Quiver"),
    STEEL_QUIVER(Mytems.STEEL_QUIVER, EquipmentVariant.QUIVER, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Quiver"),
    WOODEN_QUIVER(Mytems.WOODEN_QUIVER, EquipmentVariant.QUIVER, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Quiver"),
    EARTH_BROADSWORD(Mytems.EARTH_BROADSWORD, EquipmentVariant.BROADSWORD, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Broadsword"),
    ICE_BROADSWORD(Mytems.ICE_BROADSWORD, EquipmentVariant.BROADSWORD, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Broadsword"),
    STEEL_BROADSWORD(Mytems.STEEL_BROADSWORD, EquipmentVariant.BROADSWORD, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Broadsword"),
    SERRATED_BROADSWORD(Mytems.SERRATED_BROADSWORD, EquipmentVariant.BROADSWORD, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, (TextColor) null, "Serrated Broadsword"),
    GOLDEN_BROADSWORD(Mytems.GOLDEN_BROADSWORD, EquipmentVariant.BROADSWORD, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Broadsword"),
    GILDED_STEEL_HAMMER(Mytems.GILDED_STEEL_HAMMER, EquipmentVariant.HAMMER, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Steel Hammer"),
    STEEL_HAMMER(Mytems.STEEL_HAMMER, EquipmentVariant.HAMMER, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Hammer"),
    WOODEN_MALLET(Mytems.WOODEN_MALLET, EquipmentVariant.HAMMER, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Mallet"),
    GILDED_STEEL_MALLET(Mytems.GILDED_STEEL_MALLET, EquipmentVariant.HAMMER, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Steel Mallet"),
    STEEL_MALLET(Mytems.STEEL_MALLET, EquipmentVariant.HAMMER, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Mallet"),
    WOODEN_HAMMER(Mytems.WOODEN_HAMMER, EquipmentVariant.HAMMER, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Hammer"),
    GILDED_STEEL_CUTLASS(Mytems.GILDED_STEEL_CUTLASS, EquipmentVariant.CUTLASS, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Steel Cutlass"),
    FIRE_CUTLASS(Mytems.FIRE_CUTLASS, EquipmentVariant.CUTLASS, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Cutlass"),
    COPPER_CUTLASS(Mytems.COPPER_CUTLASS, EquipmentVariant.CUTLASS, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Copper Cutlass"),
    EARTH_CUTLASS(Mytems.EARTH_CUTLASS, EquipmentVariant.CUTLASS, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Cutlass"),
    WATER_CUTLASS(Mytems.WATER_CUTLASS, EquipmentVariant.CUTLASS, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Cutlass"),
    SERRATED_STEEL_CUTLASS(Mytems.SERRATED_STEEL_CUTLASS, EquipmentVariant.CUTLASS, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, (TextColor) null, "Serrated Steel Cutlass"),
    GILDED_STEEL_SWORD(Mytems.GILDED_STEEL_SWORD, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Steel Sword"),
    STEEL_KATANA(Mytems.STEEL_KATANA, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Katana"),
    ICE_SWORD(Mytems.ICE_SWORD, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Sword"),
    SERRATED_STEEL_SWORD(Mytems.SERRATED_STEEL_SWORD, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, (TextColor) null, "Serrated Steel Sword"),
    FIRE_SWORD(Mytems.FIRE_SWORD, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Sword"),
    STEEL_SWORD(Mytems.STEEL_SWORD, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Sword"),
    COPPER_SWORD(Mytems.COPPER_SWORD, EquipmentVariant.SWORD, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Copper Sword"),
    GILDED_WOODEN_BOW(Mytems.GILDED_WOODEN_BOW, EquipmentVariant.BOW, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Wooden Bow"),
    WOODEN_BOW(Mytems.WOODEN_BOW, EquipmentVariant.BOW, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Bow"),
    WOODEN_COMPOSITE_BOW(Mytems.WOODEN_COMPOSITE_BOW, EquipmentVariant.BOW, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Composite Bow"),
    GOLDEN_COMPOSITE_BOW(Mytems.GOLDEN_COMPOSITE_BOW, EquipmentVariant.BOW, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Composite Bow"),
    STEEL_COMPOSITE_BOW(Mytems.STEEL_COMPOSITE_BOW, EquipmentVariant.BOW, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Composite Bow"),
    WOODEN_CROSSBOW(Mytems.WOODEN_CROSSBOW, EquipmentVariant.BOW, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Crossbow"),
    VIOLET_BATTLE_SCYTHE(Mytems.VIOLET_BATTLE_SCYTHE, EquipmentVariant.SCYTHE, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Violet Battle Scythe"),
    GOLDEN_BATTLE_SCYTHE(Mytems.GOLDEN_BATTLE_SCYTHE, EquipmentVariant.SCYTHE, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Battle Scythe"),
    IRON_BATTLE_SCYTHE(Mytems.IRON_BATTLE_SCYTHE, EquipmentVariant.SCYTHE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Battle Scythe"),
    IRON_GRAND_BATTLE_SCYTHE(Mytems.IRON_GRAND_BATTLE_SCYTHE, EquipmentVariant.SCYTHE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Grand Battle Scythe"),
    STEEL_BATTLE_SCYTHE(Mytems.STEEL_BATTLE_SCYTHE, EquipmentVariant.SCYTHE, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Battle Scythe"),
    TURQUOISE_BATTLE_SCYTHE(Mytems.TURQUOISE_BATTLE_SCYTHE, EquipmentVariant.SCYTHE, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, DARK_AQUA, "Turquoise Battle Scythe"),
    RUSTY_DAGGER(Mytems.RUSTY_DAGGER, EquipmentVariant.DAGGER, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Rusty Dagger"),
    SERRATED_STEEL_DAGGER(Mytems.SERRATED_STEEL_DAGGER, EquipmentVariant.DAGGER, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, (TextColor) null, "Serrated Steel Dagger"),
    COPPER_DAGGER(Mytems.COPPER_DAGGER, EquipmentVariant.DAGGER, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Copper Dagger"),
    STEEL_NINJA_SAIS(Mytems.STEEL_NINJA_SAIS, EquipmentVariant.DAGGER, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Ninja Sais"),
    GILDED_STEEL_DAGGER(Mytems.GILDED_STEEL_DAGGER, EquipmentVariant.DAGGER, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Steel Dagger"),
    STEEL_DAGGER(Mytems.STEEL_DAGGER, EquipmentVariant.DAGGER, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Dagger"),
    ICE_WHIP(Mytems.ICE_WHIP, EquipmentVariant.WHIP, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Whip"),
    GREEN_FLAIL(Mytems.GREEN_FLAIL, EquipmentVariant.WHIP, EquipmentItemSet.NONE, EquipmentElement.EARTH, GREEN, "Green Flail"),
    FIRE_WHIP(Mytems.FIRE_WHIP, EquipmentVariant.WHIP, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Whip"),
    CHAIN_WHIP(Mytems.CHAIN_WHIP, EquipmentVariant.WHIP, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, (TextColor) null, "Chain Whip"),
    LEATHER_WHIP(Mytems.LEATHER_WHIP, EquipmentVariant.WHIP, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Leather Whip"),
    EARTH_WHIP(Mytems.EARTH_WHIP, EquipmentVariant.WHIP, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Whip"),
    SPIKED_STEEL_ROUND_SHIELD(Mytems.SPIKED_STEEL_ROUND_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Spiked Steel Round Shield"),
    CLOVER_ROUND_SHIELD(Mytems.CLOVER_ROUND_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Clover Round Shield"),
    FIRE_KITE_SHIELD(Mytems.FIRE_KITE_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Kite Shield"),
    WATER_WANKEL_SHIELD(Mytems.WATER_WANKEL_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Wankel Shield"),
    FIRE_WANKEL_SHIELD(Mytems.FIRE_WANKEL_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Wankel Shield"),
    ICE_WANKEL_SHIELD(Mytems.ICE_WANKEL_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Wankel Shield"),
    COPPER_WANKEL_SHIELD(Mytems.COPPER_WANKEL_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Copper Wankel Shield"),
    CLOVER_WANKEL_SHIELD(Mytems.CLOVER_WANKEL_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Clover Wankel Shield"),
    COPPER_ROUND_SHIELD(Mytems.COPPER_ROUND_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Copper Round Shield"),
    COATED_KITE_SHIELD(Mytems.COATED_KITE_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Coated Kite Shield"),
    STEEL_ROUND_SHIELD(Mytems.STEEL_ROUND_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Round Shield"),
    EARTH_WANKEL_SHIELD(Mytems.EARTH_WANKEL_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Wankel Shield"),
    STEEL_KITE_SHIELD(Mytems.STEEL_KITE_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Kite Shield"),
    COPPER_KITE_SHIELD(Mytems.COPPER_KITE_SHIELD, EquipmentVariant.SHIELD, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Copper Kite Shield"),
    GILDED_IRON_BATTLE_AXE(Mytems.GILDED_IRON_BATTLE_AXE, EquipmentVariant.AXE, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Iron Battle Axe"),
    SMALL_IRON_HATCHET(Mytems.SMALL_IRON_HATCHET, EquipmentVariant.AXE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Small Iron Hatchet"),
    IRON_HATCHET(Mytems.IRON_HATCHET, EquipmentVariant.AXE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Hatchet"),
    IRON_BROAD_AXE(Mytems.IRON_BROAD_AXE, EquipmentVariant.AXE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Broad Axe"),
    GILDED_IRON_MAUL(Mytems.GILDED_IRON_MAUL, EquipmentVariant.AXE, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Iron Maul"),
    STEEL_TRIDENT(Mytems.STEEL_TRIDENT, EquipmentVariant.SPEAR, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Trident"),
    GOLDEN_TRIDENT(Mytems.GOLDEN_TRIDENT, EquipmentVariant.SPEAR, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Trident"),
    WOODEN_JAVELIN(Mytems.WOODEN_JAVELIN, EquipmentVariant.SPEAR, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Javelin"),
    STEEL_SPEAR(Mytems.STEEL_SPEAR, EquipmentVariant.SPEAR, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Spear"),
    STEEL_JAVELIN(Mytems.STEEL_JAVELIN, EquipmentVariant.SPEAR, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Javelin"),
    SPIKED_WOODEN_CLUB(Mytems.SPIKED_WOODEN_CLUB, EquipmentVariant.MACE, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Spiked Wooden Club"),
    IRON_MACE(Mytems.IRON_MACE, EquipmentVariant.MACE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Mace"),
    SPIKED_IRON_MACE(Mytems.SPIKED_IRON_MACE, EquipmentVariant.MACE, EquipmentItemSet.NONE, EquipmentElement.LIGHTNING, (TextColor) null, "Spiked Iron Mace"),
    GILDED_BAT(Mytems.GILDED_BAT, EquipmentVariant.MACE, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Bat"),
    WOODEN_MACE(Mytems.WOODEN_MACE, EquipmentVariant.MACE, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Mace"),
    WOODEN_BAT(Mytems.WOODEN_BAT, EquipmentVariant.MACE, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Wooden Bat"),
    VIOLET_DOUBLE_POLEARM(Mytems.VIOLET_DOUBLE_POLEARM, EquipmentVariant.POLEARM, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Violet Double Polearm"),
    STEEL_POLEARM(Mytems.STEEL_POLEARM, EquipmentVariant.POLEARM, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Steel Polearm"),
    GOLDEN_NECKLACE_AMETHYSTS(Mytems.GOLDEN_NECKLACE_AMETHYSTS, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Necklace Amethysts"),
    GOLDEN_NECKLACE_DIAMONDS(Mytems.GOLDEN_NECKLACE_DIAMONDS, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Necklace Diamonds"),
    GOLDEN_NECKLACE_JADE(Mytems.GOLDEN_NECKLACE_JADE, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Necklace Jade"),
    LEATHER_COLLAR_GOLD_CROSS(Mytems.LEATHER_COLLAR_GOLD_CROSS, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.FREEZE, GOLD, "Leather Collar Gold Cross"),
    GOLDEN_COLLAR(Mytems.GOLDEN_COLLAR, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Collar"),
    SILVER_NECKLACE_PEARL(Mytems.SILVER_NECKLACE_PEARL, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Silver Necklace Pearl"),
    LEATHER_COLLAR(Mytems.LEATHER_COLLAR, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Leather Collar"),
    SILVER_NECKLACE_HEART(Mytems.SILVER_NECKLACE_HEART, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, (TextColor) null, "Silver Necklace Heart"),
    LEATHER_COLLAR_DIAMOND_SHARD(Mytems.LEATHER_COLLAR_DIAMOND_SHARD, EquipmentVariant.NECKLACE, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Leather Collar Diamond Shard"),
    GREEN_DECORATED_IRON_HELMET(Mytems.GREEN_DECORATED_IRON_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.NONE, EquipmentElement.EARTH, GREEN, "Green Decorated Iron Helmet"),
    DECORATED_GILDED_KING_HELMET(Mytems.DECORATED_GILDED_KING_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Decorated Gilded King Helmet"),
    BLUE_DECORATED_IRON_HELMET(Mytems.BLUE_DECORATED_IRON_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Blue Decorated Iron Helmet"),
    RED_DECORATED_IRON_HELMET(Mytems.RED_DECORATED_IRON_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, RED, "Red Decorated Iron Helmet"),
    GOLDEN_HUGE_DIAMOND_RING(Mytems.GOLDEN_HUGE_DIAMOND_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.EARTH, GOLD, "Golden Huge Diamond Ring"),
    SILVER_LINCHPIN_RING(Mytems.SILVER_LINCHPIN_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Silver Linchpin Ring"),
    GOLDEN_HEART_RING(Mytems.GOLDEN_HEART_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Golden Heart Ring"),
    SILVER_BERYL_RING(Mytems.SILVER_BERYL_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Silver Beryl Ring"),
    GOLDEN_RING(Mytems.GOLDEN_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Golden Ring"),
    SILVER_RUBY_RING(Mytems.SILVER_RUBY_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, (TextColor) null, "Silver Ruby Ring"),
    SILVER_OPAL_RING(Mytems.SILVER_OPAL_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Silver Opal Ring"),
    GOLDEN_AMETHYST_RING(Mytems.GOLDEN_AMETHYST_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.ENDER, GOLD, "Golden Amethyst Ring"),
    GOLDEN_BIG_PEARL_RING(Mytems.GOLDEN_BIG_PEARL_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, GOLD, "Golden Big Pearl Ring"),
    GOLDEN_DIAMOND_RING(Mytems.GOLDEN_DIAMOND_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.EARTH, GOLD, "Golden Diamond Ring"),
    GOLDEN_BIG_HEART_RING(Mytems.GOLDEN_BIG_HEART_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.FRIENDSHIP, GOLD, "Golden Big Heart Ring"),
    SILVER_DIAMOND_RING(Mytems.SILVER_DIAMOND_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Silver Diamond Ring"),
    GOLDEN_PEARL_RING(Mytems.GOLDEN_PEARL_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, GOLD, "Golden Pearl Ring"),
    SILVER_AND_GOLD_RINGS(Mytems.SILVER_AND_GOLD_RINGS, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.BLAZE, GOLD, "Silver And Gold Rings"),
    SILVER_RING_MISSING_GEM(Mytems.SILVER_RING_MISSING_GEM, EquipmentVariant.RING, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Silver Ring Missing Gem"),
    GOLDEN_EMERALD_RING(Mytems.GOLDEN_EMERALD_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.EARTH, GOLD, "Golden Emerald Ring"),
    SILVER_SHIELD_RING(Mytems.SILVER_SHIELD_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Silver Shield Ring"),
    SILVER_BIG_SHIELD_RING(Mytems.SILVER_BIG_SHIELD_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Silver Big Shield Ring"),
    SILVER_RING(Mytems.SILVER_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, (EquipmentElement) null, (TextColor) null, "Silver Ring"),
    GOLDEN_RUBY_RING(Mytems.GOLDEN_RUBY_RING, EquipmentVariant.RING, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, GOLD, "Golden Ruby Ring"),
    FIRE_WAND(Mytems.FIRE_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Wand"),
    RED_WAND(Mytems.RED_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, RED, "Red Wand"),
    ICE_WAND(Mytems.ICE_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Wand"),
    BLUE_WAND(Mytems.BLUE_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Blue Wand"),
    BLUE_SPARK_WAND(Mytems.BLUE_SPARK_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Blue Spark Wand"),
    PURPLE_SPARK_WAND(Mytems.PURPLE_SPARK_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Purple Spark Wand"),
    EARTH_WAND(Mytems.EARTH_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Wand"),
    WATER_WAND(Mytems.WATER_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Wand"),
    PURPLE_WAND(Mytems.PURPLE_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.ENDER, (TextColor) null, "Purple Wand"),
    RED_SPARK_WAND(Mytems.RED_SPARK_WAND, EquipmentVariant.WAND, EquipmentItemSet.NONE, EquipmentElement.BLAZE, RED, "Red Spark Wand"),
    SMALL_RED_CLOAK(Mytems.SMALL_RED_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, RED, "Small Red Cloak"),
    RED_CLOAK(Mytems.RED_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, RED, "Red Cloak"),
    BLUE_CLOAK(Mytems.BLUE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Blue Cloak"),
    ORANGE_HOODED_CLOAK(Mytems.ORANGE_HOODED_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, GOLD, "Orange Hooded Cloak"),
    SMALL_EARTH_CLOAK(Mytems.SMALL_EARTH_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Small Earth Cloak"),
    RED_HOODED_CLOAK(Mytems.RED_HOODED_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, RED, "Red Hooded Cloak"),
    FIRE_CLOAK(Mytems.FIRE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Cloak"),
    BLUE_FUR_COLLAR_CLOAK(Mytems.BLUE_FUR_COLLAR_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Blue Fur Collar Cloak"),
    EARTH_CLOAK(Mytems.EARTH_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Cloak"),
    WATER_CLOAK(Mytems.WATER_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Cloak"),
    SMALL_ICE_CLOAK(Mytems.SMALL_ICE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Small Ice Cloak"),
    ORANGE_FUR_COLOR_CLOAK(Mytems.ORANGE_FUR_COLOR_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, GOLD, "Orange Fur Color Cloak"),
    SMALL_ORANGE_CLOAK(Mytems.SMALL_ORANGE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, GOLD, "Small Orange Cloak"),
    SMALL_WATER_CLOAK(Mytems.SMALL_WATER_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Small Water Cloak"),
    RED_FUR_COLLAR_CLOAK(Mytems.RED_FUR_COLLAR_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, RED, "Red Fur Collar Cloak"),
    BLUE_HOODED_CLOAK(Mytems.BLUE_HOODED_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Blue Hooded Cloak"),
    ORANGE_CLOAK(Mytems.ORANGE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.REDSTONE, GOLD, "Orange Cloak"),
    ICE_CLOAK(Mytems.ICE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Cloak"),
    SMALL_FIRE_CLOAK(Mytems.SMALL_FIRE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Small Fire Cloak"),
    SMALL_BLUE_CLOAK(Mytems.SMALL_BLUE_CLOAK, EquipmentVariant.CLOAK, EquipmentItemSet.NONE, EquipmentElement.FREEZE, BLUE, "Small Blue Cloak"),
    WATER_SCEPTER(Mytems.WATER_SCEPTER, EquipmentVariant.SCEPTER, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Scepter"),
    EARTH_SCEPTER(Mytems.EARTH_SCEPTER, EquipmentVariant.SCEPTER, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Scepter"),
    FIRE_SCEPTER(Mytems.FIRE_SCEPTER, EquipmentVariant.SCEPTER, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Scepter"),
    ICE_SCEPTER(Mytems.ICE_SCEPTER, EquipmentVariant.SCEPTER, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Scepter"),
    EARTH_STAFF(Mytems.EARTH_STAFF, EquipmentVariant.STAFF, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Staff"),
    ICE_STAFF(Mytems.ICE_STAFF, EquipmentVariant.STAFF, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Staff"),
    FIRE_STAFF(Mytems.FIRE_STAFF, EquipmentVariant.STAFF, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Staff"),
    WATER_STAFF(Mytems.WATER_STAFF, EquipmentVariant.STAFF, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Staff"),
    WATER_CANE(Mytems.WATER_CANE, EquipmentVariant.CANE, EquipmentItemSet.NONE, EquipmentElement.GUARDIAN, (TextColor) null, "Water Cane"),
    FIRE_CANE(Mytems.FIRE_CANE, EquipmentVariant.CANE, EquipmentItemSet.NONE, EquipmentElement.BLAZE, (TextColor) null, "Fire Cane"),
    ICE_CANE(Mytems.ICE_CANE, EquipmentVariant.CANE, EquipmentItemSet.NONE, EquipmentElement.FREEZE, (TextColor) null, "Ice Cane"),
    EARTH_CANE(Mytems.EARTH_CANE, EquipmentVariant.CANE, EquipmentItemSet.NONE, EquipmentElement.EARTH, (TextColor) null, "Earth Cane"),
    GILDED_LORD_GAUNTLETS(Mytems.GILDED_LORD_GAUNTLETS, EquipmentVariant.GLOVES, EquipmentItemSet.GILDED_LORD, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Lord Gauntlets"),
    GILDED_LORD_CHESTPLATE(Mytems.GILDED_LORD_CHESTPLATE, EquipmentVariant.CHESTPLATE, EquipmentItemSet.GILDED_LORD, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Lord Chestplate"),
    GILDED_LORD_HELMET(Mytems.GILDED_LORD_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.GILDED_LORD, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Lord Helmet"),
    GILDED_LORD_GREAVES(Mytems.GILDED_LORD_GREAVES, EquipmentVariant.LEGGINGS, EquipmentItemSet.GILDED_LORD, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Lord Greaves"),
    GILDED_LORD_SABATONS(Mytems.GILDED_LORD_SABATONS, EquipmentVariant.BOOTS, EquipmentItemSet.GILDED_LORD, EquipmentElement.FRIENDSHIP, GOLD, "Gilded Lord Sabatons"),
    TURQUOISE_CLOTH_GLOVES(Mytems.TURQUOISE_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.TURQUOISE_CLOTH, EquipmentElement.GUARDIAN, DARK_AQUA, "Turquoise Cloth Gloves"),
    TURQUOISE_CLOTH_TUNIC(Mytems.TURQUOISE_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.TURQUOISE_CLOTH, EquipmentElement.GUARDIAN, DARK_AQUA, "Turquoise Cloth Tunic"),
    TURQUOISE_CLOTH_HAT(Mytems.TURQUOISE_CLOTH_HAT, EquipmentVariant.HELMET, EquipmentItemSet.TURQUOISE_CLOTH, EquipmentElement.GUARDIAN, DARK_AQUA, "Turquoise Cloth Hat"),
    TURQUOISE_CLOTH_SNEAKERS(Mytems.TURQUOISE_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.TURQUOISE_CLOTH, EquipmentElement.GUARDIAN, DARK_AQUA, "Turquoise Cloth Sneakers"),
    TURQUOISE_CLOTH_PANTS(Mytems.TURQUOISE_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.TURQUOISE_CLOTH, EquipmentElement.GUARDIAN, DARK_AQUA, "Turquoise Cloth Pants"),
    YELLOW_WINGED_CLOTH_CAP(Mytems.YELLOW_WINGED_CLOTH_CAP, EquipmentVariant.HELMET, EquipmentItemSet.YELLOW_WINGED_CLOTH, EquipmentElement.ENDER, YELLOW, "Yellow Winged Cloth Cap"),
    YELLOW_WINGED_CLOTH_GLOVES(Mytems.YELLOW_WINGED_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.YELLOW_WINGED_CLOTH, EquipmentElement.ENDER, YELLOW, "Yellow Winged Cloth Gloves"),
    YELLOW_WINGED_CLOTH_PANTS(Mytems.YELLOW_WINGED_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.YELLOW_WINGED_CLOTH, EquipmentElement.ENDER, YELLOW, "Yellow Winged Cloth Pants"),
    YELLOW_WINGED_CLOTH_TUNIC(Mytems.YELLOW_WINGED_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.YELLOW_WINGED_CLOTH, EquipmentElement.ENDER, YELLOW, "Yellow Winged Cloth Tunic"),
    YELLOW_WINGED_CLOTH_SNEAKERS(Mytems.YELLOW_WINGED_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.YELLOW_WINGED_CLOTH, EquipmentElement.ENDER, YELLOW, "Yellow Winged Cloth Sneakers"),
    STUDDED_LEATHER_GLOVES(Mytems.STUDDED_LEATHER_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.STUDDED_LEATHER, EquipmentElement.GUARDIAN, (TextColor) null, "Studded Leather Gloves"),
    STUDDED_LEATHER_BOOTS(Mytems.STUDDED_LEATHER_BOOTS, EquipmentVariant.BOOTS, EquipmentItemSet.STUDDED_LEATHER, EquipmentElement.GUARDIAN, (TextColor) null, "Studded Leather Boots"),
    STUDDED_LEATHER_HELMET(Mytems.STUDDED_LEATHER_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.STUDDED_LEATHER, EquipmentElement.GUARDIAN, (TextColor) null, "Studded Leather Helmet"),
    STUDDED_LEATHER_PANTS(Mytems.STUDDED_LEATHER_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.STUDDED_LEATHER, EquipmentElement.GUARDIAN, (TextColor) null, "Studded Leather Pants"),
    STUDDED_LEATHER_CHESTPLATE(Mytems.STUDDED_LEATHER_CHESTPLATE, EquipmentVariant.CHESTPLATE, EquipmentItemSet.STUDDED_LEATHER, EquipmentElement.GUARDIAN, (TextColor) null, "Studded Leather Chestplate"),
    ORANGE_CLOTH_GLOVES(Mytems.ORANGE_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.ORANGE_CLOTH, EquipmentElement.REDSTONE, GOLD, "Orange Cloth Gloves"),
    ORANGE_CLOTH_PANTS(Mytems.ORANGE_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.ORANGE_CLOTH, EquipmentElement.REDSTONE, GOLD, "Orange Cloth Pants"),
    ORANGE_CLOTH_HOOD(Mytems.ORANGE_CLOTH_HOOD, EquipmentVariant.HELMET, EquipmentItemSet.ORANGE_CLOTH, EquipmentElement.REDSTONE, GOLD, "Orange Cloth Hood"),
    ORANGE_CLOTH_SNEAKERS(Mytems.ORANGE_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.ORANGE_CLOTH, EquipmentElement.REDSTONE, GOLD, "Orange Cloth Sneakers"),
    ORANGE_CLOTH_TUNIC(Mytems.ORANGE_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.ORANGE_CLOTH, EquipmentElement.REDSTONE, GOLD, "Orange Cloth Tunic"),
    PEACH_CLOTH_TUNIC(Mytems.PEACH_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.PEACH_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFE5B3), "Peach Cloth Tunic"),
    PEACH_CLOTH_SNEAKERS(Mytems.PEACH_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.PEACH_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFE5B3), "Peach Cloth Sneakers"),
    PEACH_CLOTH_HOOD(Mytems.PEACH_CLOTH_HOOD, EquipmentVariant.HELMET, EquipmentItemSet.PEACH_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFE5B3), "Peach Cloth Hood"),
    PEACH_CLOTH_GLOVES(Mytems.PEACH_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.PEACH_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFE5B3), "Peach Cloth Gloves"),
    PEACH_CLOTH_PANTS(Mytems.PEACH_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.PEACH_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFE5B3), "Peach Cloth Pants"),
    IRON_KNIGHT_HELMET(Mytems.IRON_KNIGHT_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.IRON_KNIGHT, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Knight Helmet"),
    IRON_KNIGHT_GREAVES(Mytems.IRON_KNIGHT_GREAVES, EquipmentVariant.LEGGINGS, EquipmentItemSet.IRON_KNIGHT, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Knight Greaves"),
    IRON_KNIGHT_SABATONS(Mytems.IRON_KNIGHT_SABATONS, EquipmentVariant.BOOTS, EquipmentItemSet.IRON_KNIGHT, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Knight Sabatons"),
    IRON_KNIGHT_GAUNTLETS(Mytems.IRON_KNIGHT_GAUNTLETS, EquipmentVariant.GLOVES, EquipmentItemSet.IRON_KNIGHT, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Knight Gauntlets"),
    IRON_KNIGHT_CHESTPLATE(Mytems.IRON_KNIGHT_CHESTPLATE, EquipmentVariant.CHESTPLATE, EquipmentItemSet.IRON_KNIGHT, EquipmentElement.LIGHTNING, (TextColor) null, "Iron Knight Chestplate"),
    PINK_WINGED_CLOTH_HAT(Mytems.PINK_WINGED_CLOTH_HAT, EquipmentVariant.HELMET, EquipmentItemSet.PINK_WINGED_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFC0CB), "Pink Winged Cloth Hat"),
    PINK_WINGED_CLOTH_PANTS(Mytems.PINK_WINGED_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.PINK_WINGED_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFC0CB), "Pink Winged Cloth Pants"),
    PINK_WINGED_CLOTH_GLOVES(Mytems.PINK_WINGED_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.PINK_WINGED_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFC0CB), "Pink Winged Cloth Gloves"),
    PINK_WINGED_CLOTH_SNEAKERS(Mytems.PINK_WINGED_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.PINK_WINGED_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFC0CB), "Pink Winged Cloth Sneakers"),
    PINK_WINGED_CLOTH_TUNIC(Mytems.PINK_WINGED_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.PINK_WINGED_CLOTH, EquipmentElement.FRIENDSHIP, color(0xFFC0CB), "Pink Winged Cloth Tunic"),
    GREEN_FEATHER_CLOTH_TUNIC(Mytems.GREEN_FEATHER_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.GREEN_FEATHER, EquipmentElement.EARTH, GREEN, "Green Feather Cloth Tunic"),
    GREEN_FEATHER_CLOTH_CAP(Mytems.GREEN_FEATHER_CLOTH_CAP, EquipmentVariant.HELMET, EquipmentItemSet.GREEN_FEATHER, EquipmentElement.EARTH, GREEN, "Green Feather Cloth Cap"),
    GREEN_FEATHER_CLOTH_GLOVES(Mytems.GREEN_FEATHER_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.GREEN_FEATHER, EquipmentElement.EARTH, GREEN, "Green Feather Cloth Gloves"),
    GREEN_FEATHER_CLOTH_SNEAKERS(Mytems.GREEN_FEATHER_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.GREEN_FEATHER, EquipmentElement.EARTH, GREEN, "Green Feather Cloth Sneakers"),
    GREEN_FEATHER_CLOTH_PANTS(Mytems.GREEN_FEATHER_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.GREEN_FEATHER, EquipmentElement.EARTH, GREEN, "Green Feather Cloth Pants"),
    FINE_IRON_GAUNTLETS(Mytems.FINE_IRON_GAUNTLETS, EquipmentVariant.GLOVES, EquipmentItemSet.FINE_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Fine Iron Gauntlets"),
    FINE_IRON_CHESTPLATE(Mytems.FINE_IRON_CHESTPLATE, EquipmentVariant.CHESTPLATE, EquipmentItemSet.FINE_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Fine Iron Chestplate"),
    FINE_IRON_SABATONS(Mytems.FINE_IRON_SABATONS, EquipmentVariant.BOOTS, EquipmentItemSet.FINE_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Fine Iron Sabatons"),
    FINE_IRON_GREAVES(Mytems.FINE_IRON_GREAVES, EquipmentVariant.LEGGINGS, EquipmentItemSet.FINE_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Fine Iron Greaves"),
    FINE_IRON_HELMET(Mytems.FINE_IRON_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.FINE_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Fine Iron Helmet"),
    GILDED_KING_SABATONS(Mytems.GILDED_KING_SABATONS, EquipmentVariant.BOOTS, EquipmentItemSet.GILDED_KING, EquipmentElement.FRIENDSHIP, GOLD, "Gilded King Sabatons"),
    GILDED_KING_GREAVES(Mytems.GILDED_KING_GREAVES, EquipmentVariant.LEGGINGS, EquipmentItemSet.GILDED_KING, EquipmentElement.FRIENDSHIP, GOLD, "Gilded King Greaves"),
    GILDED_KING_GAUNTLETS(Mytems.GILDED_KING_GAUNTLETS, EquipmentVariant.GLOVES, EquipmentItemSet.GILDED_KING, EquipmentElement.FRIENDSHIP, GOLD, "Gilded King Gauntlets"),
    GILDED_KING_CHESTPLATE(Mytems.GILDED_KING_CHESTPLATE, EquipmentVariant.CHESTPLATE, EquipmentItemSet.GILDED_KING, EquipmentElement.FRIENDSHIP, GOLD, "Gilded King Chestplate"),
    GILDED_KING_HELMET(Mytems.GILDED_KING_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.GILDED_KING, EquipmentElement.FRIENDSHIP, GOLD, "Gilded King Helmet"),
    SIMPLE_LEATHER_PANTS(Mytems.SIMPLE_LEATHER_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.SIMPLE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Simple Leather Pants"),
    SIMPLE_LEATHER_VEST(Mytems.SIMPLE_LEATHER_VEST, EquipmentVariant.CHESTPLATE, EquipmentItemSet.SIMPLE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Simple Leather Vest"),
    SIMPLE_LEATHER_GLOVES(Mytems.SIMPLE_LEATHER_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.SIMPLE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Simple Leather Gloves"),
    SIMPLE_LEATHER_BOOTS(Mytems.SIMPLE_LEATHER_BOOTS, EquipmentVariant.BOOTS, EquipmentItemSet.SIMPLE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Simple Leather Boots"),
    SIMPLE_LEATHER_CAP(Mytems.SIMPLE_LEATHER_CAP, EquipmentVariant.HELMET, EquipmentItemSet.SIMPLE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Simple Leather Cap"),
    BASIC_IRON_GREAVES(Mytems.BASIC_IRON_GREAVES, EquipmentVariant.LEGGINGS, EquipmentItemSet.BASIC_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Basic Iron Greaves"),
    BASIC_IRON_CHESTPLATE(Mytems.BASIC_IRON_CHESTPLATE, EquipmentVariant.CHESTPLATE, EquipmentItemSet.BASIC_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Basic Iron Chestplate"),
    BASIC_IRON_HELMET(Mytems.BASIC_IRON_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.BASIC_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Basic Iron Helmet"),
    BASIC_IRON_SABATONS(Mytems.BASIC_IRON_SABATONS, EquipmentVariant.BOOTS, EquipmentItemSet.BASIC_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Basic Iron Sabatons"),
    BASIC_IRON_GAUNTLETS(Mytems.BASIC_IRON_GAUNTLETS, EquipmentVariant.GLOVES, EquipmentItemSet.BASIC_IRON, EquipmentElement.LIGHTNING, (TextColor) null, "Basic Iron Gauntlets"),
    BLUE_CLOTH_TUNIC(Mytems.BLUE_CLOTH_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.BLUE_CLOTH, EquipmentElement.FREEZE, BLUE, "Blue Cloth Tunic"),
    BLUE_CLOTH_PANTS(Mytems.BLUE_CLOTH_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.BLUE_CLOTH, EquipmentElement.FREEZE, BLUE, "Blue Cloth Pants"),
    BLUE_CLOTH_HOOD(Mytems.BLUE_CLOTH_HOOD, EquipmentVariant.HELMET, EquipmentItemSet.BLUE_CLOTH, EquipmentElement.FREEZE, BLUE, "Blue Cloth Hood"),
    BLUE_CLOTH_SNEAKERS(Mytems.BLUE_CLOTH_SNEAKERS, EquipmentVariant.BOOTS, EquipmentItemSet.BLUE_CLOTH, EquipmentElement.FREEZE, BLUE, "Blue Cloth Sneakers"),
    BLUE_CLOTH_GLOVES(Mytems.BLUE_CLOTH_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.BLUE_CLOTH, EquipmentElement.FREEZE, BLUE, "Blue Cloth Gloves"),
    FINE_LEATHER_PANTS(Mytems.FINE_LEATHER_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.FINE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Fine Leather Pants"),
    FINE_LEATHER_BOOTS(Mytems.FINE_LEATHER_BOOTS, EquipmentVariant.BOOTS, EquipmentItemSet.FINE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Fine Leather Boots"),
    FINE_LEATHER_VEST(Mytems.FINE_LEATHER_VEST, EquipmentVariant.CHESTPLATE, EquipmentItemSet.FINE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Fine Leather Vest"),
    FINE_LEATHER_GLOVES(Mytems.FINE_LEATHER_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.FINE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Fine Leather Gloves"),
    FINE_LEATHER_HELMET(Mytems.FINE_LEATHER_HELMET, EquipmentVariant.HELMET, EquipmentItemSet.FINE_LEATHER, EquipmentElement.FREEZE, (TextColor) null, "Fine Leather Helmet"),
    BLUE_JESTER_PANTS(Mytems.BLUE_JESTER_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.BLUE_JESTER, EquipmentElement.FREEZE, BLUE, "Blue Jester Pants"),
    BLUE_JESTER_GLOVES(Mytems.BLUE_JESTER_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.BLUE_JESTER, EquipmentElement.FREEZE, BLUE, "Blue Jester Gloves"),
    BLUE_JESTER_HAT(Mytems.BLUE_JESTER_HAT, EquipmentVariant.HELMET, EquipmentItemSet.BLUE_JESTER, EquipmentElement.FREEZE, BLUE, "Blue Jester Hat"),
    BLUE_JESTER_SHOES(Mytems.BLUE_JESTER_SHOES, EquipmentVariant.BOOTS, EquipmentItemSet.BLUE_JESTER, EquipmentElement.FREEZE, BLUE, "Blue Jester Shoes"),
    BLUE_JESTER_TUNIC(Mytems.BLUE_JESTER_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.BLUE_JESTER, EquipmentElement.FREEZE, BLUE, "Blue Jester Tunic"),
    RED_JESTER_GLOVES(Mytems.RED_JESTER_GLOVES, EquipmentVariant.GLOVES, EquipmentItemSet.RED_JESTER, EquipmentElement.REDSTONE, RED, "Red Jester Gloves"),
    RED_JESTER_HAT(Mytems.RED_JESTER_HAT, EquipmentVariant.HELMET, EquipmentItemSet.RED_JESTER, EquipmentElement.REDSTONE, RED, "Red Jester Hat"),
    RED_JESTER_TUNIC(Mytems.RED_JESTER_TUNIC, EquipmentVariant.CHESTPLATE, EquipmentItemSet.RED_JESTER, EquipmentElement.REDSTONE, RED, "Red Jester Tunic"),
    RED_JESTER_SHOES(Mytems.RED_JESTER_SHOES, EquipmentVariant.BOOTS, EquipmentItemSet.RED_JESTER, EquipmentElement.REDSTONE, RED, "Red Jester Shoes"),
    RED_JESTER_PANTS(Mytems.RED_JESTER_PANTS, EquipmentVariant.CHESTPLATE, EquipmentItemSet.RED_JESTER, EquipmentElement.REDSTONE, RED, "Red Jester Pants"),
    ;

    public final Mytems mytems;
    public final EquipmentVariant variant;
    public final EquipmentItemSet itemSet;
    public final EquipmentElement element;
    public final TextColor textColor;
    public final String displayName;

    public TextColor getTextColor() {
        return textColor != null
            ? textColor
            : (element != null
               ? element.textColor
               : WHITE);
    }

    private static final Map<Mytems, EquipmentType> MYTEMS_MAP = new HashMap<>();

    static {
        for (EquipmentType it : values()) {
            MYTEMS_MAP.put(it.mytems, it);
        }
    }

    public static EquipmentType of(Mytems mytems) {
        return MYTEMS_MAP.get(mytems);
    }
}
